services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped  # Контейнер будет подниматься сам после перезагрузки
    ports:
      - "127.0.0.1:5432:5432"  # База доступна только локально внутри сервера
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Правильный путь для сохранения данных

  # Оставляем pgAdmin, но его пароли тоже прячем
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data: