"""unique material variant name

Revision ID: 2d77f5d29c07
Revises: 836c86fe8a3d
Create Date: 2026-08-10 17:57:20.724319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d77f5d29c07'
down_revision: Union[str, Sequence[str], None] = '836c86fe8a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_material_variant_name', 'material_variants', ['material_id', 'name_variant'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_material_variant_name', 'material_variants', type_='unique')
    # ### end Alembic commands ###
